### ISSUE TITLE
D49E Manufacturer

### ISSUE THREAD

**Issue by Be4stElectrjc** [JoeyStrandnes/EVB_500-Throttle#1]
Are you sure that the manufacturer is YZPST? In the datasheet the marking doesn't match.

All the best

**Comment by JoeyStrandnes** [comment]
Hi, 

I'm not completely certain that they are the manufacturer but they were the only one that I could find that produced a linear hall-effect sensor in that package, pinout and markings. 
- The package is the same.
- Pinout is the same (legs were ripped off but the cable connections were connected to the correct pinout).
- Marking was almost the same, only differing very slightly. 

The electrical properties were also tested and throttle voltages corresponded with the hall-effect datasheet as can be seen in the [Software chapter](https://github.com/JoeyStrandnes/EVB_500-Throttle#the-microcontroller-polls-the-pin-that-the-button-is-connected-the-microcontroller-outputs-a-pwm-value-of-09v--if-the-button-is-not-pressed-running-function-stopmotor-the-microcontroller-will-output-a-pwm-value-matching-42v-if-it-detects-a-button-press-running-function-startmotor) and on page 4 in the datasheet.

Have you found a better suiting sensor?

Regards
Joseph

The below image is of the sensor and datasheet.
![Hall](https://i.imgur.com/veijvgX.png)

**Comment by Be4stElectrjc** [comment]
There are a lot of manufacturers for the 49E and products are similar, although not identical. Asked high-resolution photos of their [product](https://www.globalsources.com/Magnetic-sensor/Hall-Effect-Linear-Position-Sensor-1139513440p.htm), but even the marking indicated in the datasheet shows three characters (49E) like all other vendors do.

**Comment by JoeyStrandnes** [comment]
Interesting, I believe that the one I found was the only one available Chinese electronic retailers. This was also three years ago so they don't seem be sell them anymore.

I wouldn't be too worried about the manufacturer though, it seems to be a jellybean component with quite simple specifications.
An alternative would be to replace the throttle with a generic electric scooter thumb throttle and slightly modify my code for the variable speed. Make sure to convert the 0-5V signal from the scooter throttle to a 0.9-4.2V signal for the EVB-500, this can be done with my mod.
Might add that using a button isn't as bad as it might seem, its a very simple fix but works pretty well.

![Generic throttle](https://i.ebayimg.com/images/g/sm0AAOSwv69jqyNr/s-l500.jpg)

**Comment by Be4stElectrjc** [comment]
It was just to find the right manufacturer, curiosity.
